## This is the configuration file

[Inputs]
# radionuclide and half life in s
rad = "S-35" 
t05 = 7.538E6
ut05 = 0.013E6

# laboratory
laboratory = "LAB"
year = 2025

# Birks constant (cm/keV)
kb = 0.8e-5 
kbmin = 0.5e-5
kbmax = 1.2e-5

# quantum efficiency
quantum_efficiency_pmta = 0.25
quantum_efficiency_pmtb = 0.25
quantum_efficiency_pmtc = 0.25

daq = "nanoTDCR"
# DSP parameters
#        1. for the extended time 1 (50 µs) and resolution time 1 (50 ns) 
#        2. for the extended time 1 (50 µs) and resolution time 2 (100 ns) 
#        3. for the extended time 2 (10 µs) and resolution time 1 (50 ns) 
#        4. for the extended time 2 (10 µs) and resolution time 2 (100 ns)
dsp_params = 3

# Reference date
# TC-99 reference date (Y,M,D,h,m,s) LNHB 2025
ref_date = 2025-11-25 12:00:00

# Mass of the Tc-99 source /g
source_name = "AB1"
grey_filter_nd = 0
diffusive_vial = True
mass_g = 0.174537
u_mass_g = 0.000005
total_source_vol_ml = 15
ls_cocktail = "Ultima Gold AB"
frac_aq = 0.174537/15
solvant = "HCl"
solvant_conc = 0.1
# Path of the background
path_ntd_bck = "inputs\S-35\S_0_0.tdc"
# Path of the source
path_ntd_src = "inputs\S-35\S_1_0.tdc"